version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db:/var/lib/postgresql/data

  airflow:
    build: ./airflow
    env_file:
      - ./stack.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: K6HtnPhEhPZrbn3mKcYUVrdbNJzzFDhJ9n5AbsXbJo=
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: >
      bash -c "airflow db migrate &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
               airflow webserver"
    ports:
      - "8081:8080"

  airflow_scheduler:
    build: ./airflow
    env_file:
      - ./stack.env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: K6HtnPhEhPZrbn3mKcYUVrdbNJzzFDhJ9n5AbsXbJo=
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - /home/umbrel/umbrel/app-data/portainer/data/docker/compose/8/airflow/dags:/opt/airflow/dags
    command: airflow scheduler

  streamlit_dashboard:
    build: ./streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit:/app
    command: streamlit run home.py --server.port=8501 --server.enableXsrfProtection=false


volumes:
  postgres-db: